# Generated by Django 3.2.23 on 2023-12-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_auto_20231227_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='merchant_logo',
            field=models.URLField(blank=True),
        ),
    ]
