# Generated by Django 3.2.23 on 2023-12-28 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_type'),
        ('merchants', '0003_alter_merchant_merchant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
